# Generated by Django 2.2.6 on 2019-10-26 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.TextField(max_length=200, verbose_name='画像リンク')),
                ('text', models.TextField(max_length=1000, verbose_name='コメント')),
                ('result', models.IntegerField(verbose_name='表示する場合の結果')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='更新日時')),
                ('like_num', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hand', models.IntegerField(verbose_name='自分の手')),
                ('opponent_hand', models.IntegerField(verbose_name='相手の手')),
                ('result', models.IntegerField(verbose_name='勝負結果')),
                ('match_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='マッチタイム')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='janken.Response', verbose_name='レスポンス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janken.Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
