# Generated by Django 2.2.6 on 2019-10-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
