# Generated by Django 2.2.6 on 2019-10-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0003_auto_20191026_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='janken.Response', verbose_name='レスポンス'),
        ),
        migrations.AlterField(
            model_name='response',
            name='image_link',
            field=models.TextField(max_length=2000, verbose_name='画像リンク'),
        ),
        migrations.AlterField(
            model_name='response',
            name='result',
            field=models.IntegerField(verbose_name='janken結果'),
        ),
    ]
