# Generated by Django 2.2.6 on 2019-10-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0006_auto_20191027_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='view_num',
            field=models.IntegerField(default=0),
        ),
    ]
