# Generated by Django 2.2.6 on 2019-10-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0007_response_view_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='image_link',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='画像URL'),
        ),
    ]
